version: "3.7"

services:
  backend:
    build: ./mobility-notebooks
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan
    depends_on:
      - db

  db:
    image: codewit/mobilitydb
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
